### ISSUE TITLE
README

### ISSUE THREAD

**Issue by nubonics** [ASAS1314/playwright_stealth#3]
The readme results for a headless check are backwards
With stealth should show (as ive tested recently) that it passes the headless check

Without stealth should show (as ive tested) that it fails many of the tests

**Comment by ASAS1314** [comment]
> The readme results for a headless check are backwards
> With stealth should show (as ive tested recently) that it passes the headless check
> 
> Without stealth should show (as ive tested) that it fails many of the tests


updated already.
